name: XYZ

on:
  push:
    branches:
      - release/xyz

jobs:
  deploy-xyz:
    name: Deploy on .XYZ
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [ '/anywhere' ]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: release/xyz

      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          host: 'host.nibol.xyz'
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/anywhere
            git checkout .
            git checkout release/xyz
            git pull

      - name: Install and build
        uses: appleboy/ssh-action@master
        with:
          host: 'host.nibol.xyz'
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/anywhere
            pnpm i
            pnpm database:generate
            pnpm database:migrate
            pnpm build

      - name: Restart PM2 processes
        uses: appleboy/ssh-action@master
        with:
          host: 'host.nibol.xyz'
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/anywhere
            pm2 delete all
            cd ~/anywhere/apps/api
            pm2 start ecosystem.config.js
            cd ~/anywhere/apps/host
            pm2 start ecosystem.config.cjs
            pm2 save

        env:
          CI: 'true'